// Hidden Thread — Season One
// 60 original puzzles: 20 Easy, 20 Moderate, 20 Hard.
// Each puzzle contains exactly 48 letters after spaces and punctuation are removed.

export const PUZZLES = [
  {
    id: "E01",
    difficulty: "easy",
    title: "Rise & Dine",
    clue: "Start the day with these familiar breakfast favorites.",
    masterThread: "BREAKFAST",
    words: ["PANCAKE", "WAFFLE", "CEREAL", "TOAST", "BACON", "YOGURT", "EGGS"],
  },
  {
    id: "E02",
    difficulty: "easy",
    title: "Shore Thing",
    clue: "Pack these things for a classic day at the beach.",
    masterThread: "BEACH FUN",
    words: ["SANDCASTLE", "SUNSCREEN", "TOWEL", "SHELL", "WAVES", "BUCKET"],
  },
  {
    id: "E03",
    difficulty: "easy",
    title: "Drip, Drop!",
    clue: "These are familiar sights and gear from a rainy day.",
    masterThread: "RAINY DAY",
    words: ["UMBRELLA", "PUDDLE", "RAINCOAT", "BOOTS", "CLOUDS", "THUNDER"],
  },
  {
    id: "E04",
    difficulty: "easy",
    title: "Dig It!",
    clue: "Find the things that help a garden grow.",
    masterThread: "GARDENING",
    words: ["FLOWERS", "SHOVEL", "SEEDS", "WATERING", "WEEDS", "SOIL", "HOSE"],
  },
  {
    id: "E05",
    difficulty: "easy",
    title: "Ready for Class",
    clue: "These useful items belong at school.",
    masterThread: "CLASSROOM",
    words: ["PENCIL", "ERASER", "RULER", "NOTEBOOK", "CRAYON", "BACKPACK"],
  },
  {
    id: "E06",
    difficulty: "easy",
    title: "Lights Out",
    clue: "These cozy things are part of getting ready to sleep.",
    masterThread: "BEDTIME",
    words: ["PILLOW", "BLANKET", "PAJAMAS", "STORY", "NIGHTLIGHT", "DREAMS"],
  },
  {
    id: "E07",
    difficulty: "easy",
    title: "Slice of Fun",
    clue: "These favorites belong at a pizza night.",
    masterThread: "PIZZA NIGHT",
    words: ["CHEESE", "SAUCE", "CRUST", "MUSHROOMS", "PEPPERONI", "OVEN"],
  },
  {
    id: "E08",
    difficulty: "easy",
    title: "Wild Neighbors",
    clue: "Meet these familiar animals from around the world.",
    masterThread: "WILDLIFE",
    words: ["ELEPHANT", "GIRAFFE", "MONKEY", "ZEBRA", "TIGER", "CROCODILE"],
  },
  {
    id: "E09",
    difficulty: "easy",
    title: "Sweet Mix",
    clue: "Gather these basics before baking a batch of treats.",
    masterThread: "BAKING",
    words: ["FLOUR", "SUGAR", "BUTTER", "OVEN", "COOKIES", "APRON", "WHISK", "DOUGH"],
  },
  {
    id: "E10",
    difficulty: "easy",
    title: "Make Some Noise",
    clue: "These instruments and ideas help people make music.",
    masterThread: "MUSIC MAKER",
    words: ["GUITAR", "DRUMS", "PIANO", "SINGER", "MELODY", "RHYTHM", "HARP"],
  },
  {
    id: "E11",
    difficulty: "easy",
    title: "Happy Campers",
    clue: "Pack these familiar essentials for a night outdoors.",
    masterThread: "CAMPING",
    words: ["TENT", "CAMPFIRE", "FLASHLIGHT", "BACKPACK", "TRAIL", "FOREST"],
  },
  {
    id: "E12",
    difficulty: "easy",
    title: "Color Parade",
    clue: "Find these familiar colors from a painter’s color chart.",
    masterThread: "COLOR CHART",
    words: ["ORANGE", "YELLOW", "GREEN", "PURPLE", "VIOLET", "BLUE", "BLACK"],
  },
  {
    id: "E13",
    difficulty: "easy",
    title: "Clean Sweep",
    clue: "These are familiar jobs that help tidy a home.",
    masterThread: "CHORE TIME",
    words: ["VACUUM", "DUSTING", "LAUNDRY", "WASHING", "SWEEP", "MOPPING"],
  },
  {
    id: "E14",
    difficulty: "easy",
    title: "Bowl Mates",
    clue: "Pick the fruits you might toss into a colorful bowl.",
    masterThread: "FRUIT BOWL",
    words: ["APPLE", "BANANA", "ORANGE", "GRAPES", "PEACH", "MELON", "CHERRY"],
  },
  {
    id: "E15",
    difficulty: "easy",
    title: "Recess Rules",
    clue: "Find the games and equipment waiting on a playground.",
    masterThread: "PLAYGROUND",
    words: ["SWING", "SLIDE", "SEESAW", "SANDBOX", "MONKEY BARS", "CHASE"],
  },
  {
    id: "E16",
    difficulty: "easy",
    title: "Kitchen Helpers",
    clue: "A cook reaches for these useful kitchen tools.",
    masterThread: "KITCHEN TOOLS",
    words: ["SPATULA", "WHISK", "STRAINER", "LADLE", "TONGS", "PEELER"],
  },
  {
    id: "E17",
    difficulty: "easy",
    title: "On the Move",
    clue: "These familiar rides help people get from place to place.",
    masterThread: "GETTING AROUND",
    words: ["BICYCLE", "SCOOTER", "TRAINS", "SUBWAY", "TAXI", "FERRY"],
  },
  {
    id: "E18",
    difficulty: "easy",
    title: "Happy Pet",
    clue: "These everyday things help keep a pet happy and healthy.",
    masterThread: "PET CARE",
    words: ["LEASH", "COLLAR", "KIBBLE", "WATER", "BRUSH", "TREATS", "PLAYTIME"],
  },
  {
    id: "E19",
    difficulty: "easy",
    title: "Down on the Farm",
    clue: "Meet the familiar animals and sights around a farmyard.",
    masterThread: "FARMYARD",
    words: ["CHICKEN", "CATTLE", "HORSE", "SHEEP", "GOAT", "PIGS", "DUCKS", "BARN"],
  },
  {
    id: "E20",
    difficulty: "easy",
    title: "Cart Smart",
    clue: "Spot the familiar things you meet while grocery shopping.",
    masterThread: "SHOPPING",
    words: ["CART", "AISLE", "CASHIER", "PRODUCE", "BAKERY", "COUPON", "PRICE"],
  },

  {
    id: "M01",
    difficulty: "moderate",
    title: "A Stitch in Time",
    clue: "A well-stocked sewing basket would recognize this whole set.",
    masterThread: "NEEDLEWORK",
    words: ["THIMBLE", "BUTTON", "SCISSORS", "STITCH", "SPOOL", "FABRIC"],
  },
  {
    id: "M02",
    difficulty: "moderate",
    title: "Say Ahh",
    clue: "A clean, healthy smile depends on this familiar lineup.",
    masterThread: "DENTAL CARE",
    words: ["TOOTHBRUSH", "FLOSS", "MOLARS", "ENAMEL", "CAVITY", "RINSE"],
  },
  {
    id: "M03",
    difficulty: "moderate",
    title: "Now You See It",
    clue: "A performer might use these to make the impossible look effortless.",
    masterThread: "STAGE MAGIC",
    words: ["WANDS", "RABBIT", "COINS", "ESCAPE", "VANISH", "TRICK", "DOVES"],
  },
  {
    id: "M04",
    difficulty: "moderate",
    title: "Recipe Orders",
    clue: "Each could be the next command in a recipe.",
    masterThread: "COOKING",
    words: ["CHOP", "SLICE", "GRATE", "WHISK", "KNEAD", "SIMMER", "ROAST", "SEASON"],
  },
  {
    id: "M05",
    difficulty: "moderate",
    title: "Paper Trail",
    clue: "These desk-drawer and correspondence companions keep messages moving.",
    masterThread: "STATIONERY",
    words: ["ENVELOPE", "LETTER", "STAMP", "NOTEPAD", "PENCIL", "ERASER"],
  },
  {
    id: "M06",
    difficulty: "moderate",
    title: "Now Showing",
    clue: "Find what surrounds the story before, during, and after the feature.",
    masterThread: "CINEMA",
    words: ["POPCORN", "TRAILER", "SCREEN", "TICKET", "USHER", "CREDITS", "SEAT"],
  },
  {
    id: "M07",
    difficulty: "moderate",
    title: "How Much?",
    clue: "Each answers a different version of the question, “How much?”",
    masterThread: "MEASURING",
    words: ["LENGTH", "HEIGHT", "WEIGHT", "VOLUME", "SPEED", "DEPTH", "WIDTH"],
  },
  {
    id: "M08",
    difficulty: "moderate",
    title: "Tiny Garden Guests",
    clue: "They flutter, crawl, or chirp among the leaves.",
    masterThread: "GARDEN VISITORS",
    words: ["BUTTERFLY", "LADYBUG", "BEETLES", "CRICKET", "MOTH"],
  },
  {
    id: "M09",
    difficulty: "moderate",
    title: "Workbench Lineup",
    clue: "This lineup offers grip, striking power, and sharp edges.",
    masterThread: "HAND TOOLS",
    words: ["HAMMER", "WRENCH", "PLIERS", "CHISEL", "LEVEL", "DRILL", "FILES"],
  },
  {
    id: "M10",
    difficulty: "moderate",
    title: "Read the Rhythm",
    clue: "These marks and directions tell musicians what and how to play.",
    masterThread: "MUSICAL SCORE",
    words: ["CLEF", "REST", "STAFF", "TEMPO", "RHYTHM", "CHORD", "MEASURE"],
  },
  {
    id: "M11",
    difficulty: "moderate",
    title: "Take Five",
    clue: "An order, a snack, and the person serving them all fit this pause.",
    masterThread: "COFFEE BREAK",
    words: ["ESPRESSO", "LATTE", "MOCHA", "MUFFIN", "COOKIE", "BARISTA"],
  },
  {
    id: "M12",
    difficulty: "moderate",
    title: "Beyond the Launchpad",
    clue: "A journey above the atmosphere meets all of these along the way.",
    masterThread: "SPACE TRAVEL",
    words: ["PLANETS", "COMET", "ORBIT", "ROCKET", "ASTEROID", "MODULE"],
  },
  {
    id: "M13",
    difficulty: "moderate",
    title: "Between the Covers",
    clue: "A reader can meet each one without leaving a single volume.",
    masterThread: "BOOK ANATOMY",
    words: ["COVER", "SPINE", "CHAPTER", "INDEX", "PREFACE", "GLOSSARY"],
  },
  {
    id: "M14",
    difficulty: "moderate",
    title: "Which Way?",
    clue: "Together they turn “Where am I?” into “This way.”",
    masterThread: "WAYFINDER",
    words: ["COMPASS", "LANDMARK", "DIRECTION", "TRAIL", "GUIDE", "ROUTE"],
  },
  {
    id: "M15",
    difficulty: "moderate",
    title: "A Little Off the Top",
    clue: "These belong in the chair-side routine that leaves you looking sharper.",
    masterThread: "BARBERSHOP",
    words: ["CLIPPERS", "CAPE", "COMB", "MIRROR", "SHAMPOO", "TRIM", "STYLE"],
  },
  {
    id: "M16",
    difficulty: "moderate",
    title: "Tabletop Contest",
    clue: "These shape a tabletop contest from setup to final tally.",
    masterThread: "GAME NIGHT",
    words: ["DICE", "TOKEN", "BOARD", "CARDS", "MOVES", "SCORE", "RULES", "PAWNS"],
  },
  {
    id: "M17",
    difficulty: "moderate",
    title: "In Focus",
    clue: "These help turn a framed moment into a lasting image.",
    masterThread: "PHOTOGRAPHY",
    words: ["CAMERAS", "LENS", "FLASH", "TRIPOD", "SHUTTER", "PORTRAIT"],
  },
  {
    id: "M18",
    difficulty: "moderate",
    title: "Passing Hours",
    clue: "Each has its own way to divide, display, or announce passing hours.",
    masterThread: "TIMEKEEPING",
    words: ["CLOCKS", "WATCH", "SUNDIAL", "HOURGLASS", "TIMER", "ALARM"],
  },
  {
    id: "M19",
    difficulty: "moderate",
    title: "Room Inside",
    clue: "Their shared talent is keeping other things inside.",
    masterThread: "CONTAINER",
    words: ["BASKET", "BOTTLE", "BUCKET", "CARTON", "POUCH", "WALLET", "TOTE"],
  },
  {
    id: "M20",
    difficulty: "moderate",
    title: "Under the Canopy",
    clue: "Look beneath the trees for a collection that crunches, cushions, or sprouts.",
    masterThread: "FOREST FLOOR",
    words: ["ACORNS", "MOSS", "LEAVES", "TWIGS", "MUSHROOM", "PINECONE"],
  },

  {
    id: "H01",
    difficulty: "hard",
    title: "Same Old Pull",
    clue: "Pull, inhale, infer, unsheathe—the same verb quietly does all the work.",
    masterThread: "CAN BE DRAWN",
    words: ["CURTAIN", "BATH", "BREATH", "CONCLUSION", "SWORD", "SALARY"],
  },
  {
    id: "H02",
    difficulty: "hard",
    title: "One Word Down",
    clue: "Each answer can take the same four-letter tumble.",
    masterThread: "FOLLOWED BY FALL",
    words: ["WATER", "NIGHT", "DOWN", "WIND", "FOOT", "RAIN", "SNOW", "FREE"],
  },
  {
    id: "H03",
    difficulty: "hard",
    title: "Round About",
    clue: "Growth, calls, combat, performance, table settings, and grime all come full circle.",
    masterThread: "RING CONNECTION",
    words: ["TREE", "PHONE", "BOXING", "CIRCUS", "NAPKIN", "BATHTUB"],
  },
  {
    id: "H04",
    difficulty: "hard",
    title: "Make the Pitch",
    clue: "A diamond, a deal, and a note all lean on the same word.",
    masterThread: "PITCH LINK",
    words: ["FIELD", "SALES", "MUSIC", "ROOF", "TENT", "DARK", "NOTE", "BASEBALL"],
  },
  {
    id: "H05",
    difficulty: "hard",
    title: "Quiet Company",
    clue: "Each answer carries at least one letter that refuses to introduce itself.",
    masterThread: "SILENT LETTER",
    words: ["GNOME", "KNIGHT", "PSALM", "WRIST", "HONOR", "DEBT", "ISLAND"],
  },
  {
    id: "H06",
    difficulty: "hard",
    title: "Get on Board",
    clue: "Place the same five-letter word after each answer.",
    masterThread: "BOARD SUFFIX",
    words: ["CARD", "SKATE", "SURF", "DASH", "BLACK", "SCORE", "CHESS", "STORY"],
  },
  {
    id: "H07",
    difficulty: "hard",
    title: "Hit List",
    clue: "One verb can ignite, resonate, negotiate, model, discover, ring, or calibrate these.",
    masterThread: "COMMON STRIKE",
    words: ["MATCH", "CHORD", "BARGAIN", "POSE", "GOLD", "BELL", "BALANCE"],
  },
  {
    id: "H08",
    difficulty: "hard",
    title: "Down in Front",
    clue: "Put the same lowly prefix ahead of each answer.",
    masterThread: "LEADS WITH UNDER",
    words: ["COVER", "GROUND", "STUDY", "WORLD", "WEAR", "TONE", "SCORE"],
  },
  {
    id: "H09",
    difficulty: "hard",
    title: "Sheet Followers",
    clue: "A thin sheet goes before every answer to make a familiar term.",
    masterThread: "PAPER COMPANIONS",
    words: ["CLIP", "BACK", "WORK", "WEIGHT", "TRAIL", "TIGER", "PLANE"],
  },
  {
    id: "H10",
    difficulty: "hard",
    title: "Ahead of Themselves",
    clue: "Look for the part shared by greens, percussion, hardware, and loose change.",
    masterThread: "HEAD HOLDERS",
    words: ["CABBAGE", "LETTUCE", "COIN", "NAIL", "DRUM", "MATCH", "HAMMER"],
  },
  {
    id: "H11",
    difficulty: "hard",
    title: "Different Paces",
    clue: "One motion describes plumbing, software, sniffles, hosiery, machinery, and waterways.",
    masterThread: "RUNNING THREAD",
    words: ["WATER", "ENGINE", "NOSE", "STOCKING", "PROGRAM", "RIVER"],
  },
  {
    id: "H12",
    difficulty: "hard",
    title: "Interest-Free",
    clue: "No money is required at any of these banks.",
    masterThread: "BANK CONNECTION",
    words: ["RIVER", "SNOW", "BLOOD", "FOOD", "MEMORY", "POWER", "CLOUD"],
  },
  {
    id: "H13",
    difficulty: "hard",
    title: "Give Me a Break",
    clue: "Put one five-letter pause before each answer and new terms appear.",
    masterThread: "BREAK BEFORE",
    words: ["FAST", "AWAY", "THROUGH", "DOWN", "WATER", "POINT", "EVEN", "NECK"],
  },
  {
    id: "H14",
    difficulty: "hard",
    title: "Bright Sidekicks",
    clue: "A single bright word can precede all eight answers.",
    masterThread: "AFTER LIGHT",
    words: ["HOUSE", "BULB", "YEAR", "WEIGHT", "HEARTED", "WAVE", "DUTY", "SHOW"],
  },
  {
    id: "H15",
    difficulty: "hard",
    title: "Scarlet Attachments",
    clue: "Color every answer the same way and familiar phrases appear.",
    masterThread: "RED THREAD",
    words: ["CARPET", "HERRING", "TAPE", "FLAG", "ALERT", "BRICK", "WINE", "MEAT"],
  },
  {
    id: "H16",
    difficulty: "hard",
    title: "Wild Company",
    clue: "A parade, vanity, and a collision become company in the wild.",
    masterThread: "ANIMAL GROUPS",
    words: ["PARADE", "PRIDE", "CRASH", "SCHOOL", "FLOCK", "SWARM", "HERD"],
  },
  {
    id: "H17",
    difficulty: "hard",
    title: "Key Differences",
    clue: "Some open doors, while others open code, commands, or music.",
    masterThread: "KEY VARIETY",
    words: ["PIANO", "CIPHER", "IGNITION", "SKELETON", "ESCAPE", "SHIFT"],
  },
  {
    id: "H18",
    difficulty: "hard",
    title: "Go With It",
    clue: "From veins to networks to rush hour, each answer keeps moving.",
    masterThread: "WHAT FLOWS",
    words: ["WATER", "TRAFFIC", "LAVA", "TIME", "IDEAS", "MONEY", "BLOOD", "DATA"],
  },
  {
    id: "H19",
    difficulty: "hard",
    title: "Under Pressure",
    clue: "One sharp word unlocks, amuses, sounds, and splits its partners.",
    masterThread: "CRACK PARTNERS",
    words: ["CODE", "JOKE", "WHIP", "CASE", "SAFE", "DAWN", "NUTS", "KNUCKLE"],
  },
  {
    id: "H20",
    difficulty: "hard",
    title: "Higher Calling",
    clue: "These can all go up without an elevator.",
    masterThread: "ALL GET RAISED",
    words: ["EYEBROWS", "CASH", "ROOF", "STAKES", "VOICE", "ALARM", "HAND"],
  },
];
